apiVersion: security.rancher.io/v1alpha1
kind: WorkloadPolicy
metadata:
  name: bench-policy-${index}
  namespace: ${namespace}
spec:
  mode: monitor
  rulesByContainer:
    bench:
      executables:
        allowed:
        - /usr/bin/sleep
        - /usr/bin/bash
        - /usr/bin/groups
        - /usr/bin/dircolors
        - /usr/bin/tail
        - /usr/bin/mawk
        - /usr/local/bin/perf
        - /usr/bin/true
        - /usr/bin/true1
        - /usr/bin/true2
