//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicy) DeepCopyInto(out *WorkloadPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicy.
func (in *WorkloadPolicy) DeepCopy() *WorkloadPolicy {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyExecutables) DeepCopyInto(out *WorkloadPolicyExecutables) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AllowedPrefixes != nil {
		in, out := &in.AllowedPrefixes, &out.AllowedPrefixes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyExecutables.
func (in *WorkloadPolicyExecutables) DeepCopy() *WorkloadPolicyExecutables {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyExecutables)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyList) DeepCopyInto(out *WorkloadPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyList.
func (in *WorkloadPolicyList) DeepCopy() *WorkloadPolicyList {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposal) DeepCopyInto(out *WorkloadPolicyProposal) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposal.
func (in *WorkloadPolicyProposal) DeepCopy() *WorkloadPolicyProposal {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPolicyProposal) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalCondition) DeepCopyInto(out *WorkloadPolicyProposalCondition) {
	*out = *in
	in.LastProbeTime.DeepCopyInto(&out.LastProbeTime)
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalCondition.
func (in *WorkloadPolicyProposalCondition) DeepCopy() *WorkloadPolicyProposalCondition {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalList) DeepCopyInto(out *WorkloadPolicyProposalList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadPolicyProposal, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalList.
func (in *WorkloadPolicyProposalList) DeepCopy() *WorkloadPolicyProposalList {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadPolicyProposalList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalSpec) DeepCopyInto(out *WorkloadPolicyProposalSpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RulesByContainer != nil {
		in, out := &in.RulesByContainer, &out.RulesByContainer
		*out = make(map[string]*WorkloadPolicyRules, len(*in))
		for key, val := range *in {
			var outVal *WorkloadPolicyRules
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(WorkloadPolicyRules)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalSpec.
func (in *WorkloadPolicyProposalSpec) DeepCopy() *WorkloadPolicyProposalSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyProposalStatus) DeepCopyInto(out *WorkloadPolicyProposalStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]WorkloadPolicyProposalCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyProposalStatus.
func (in *WorkloadPolicyProposalStatus) DeepCopy() *WorkloadPolicyProposalStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyProposalStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyRules) DeepCopyInto(out *WorkloadPolicyRules) {
	*out = *in
	in.Executables.DeepCopyInto(&out.Executables)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyRules.
func (in *WorkloadPolicyRules) DeepCopy() *WorkloadPolicyRules {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicySpec) DeepCopyInto(out *WorkloadPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.RulesByContainer != nil {
		in, out := &in.RulesByContainer, &out.RulesByContainer
		*out = make(map[string]*WorkloadPolicyRules, len(*in))
		for key, val := range *in {
			var outVal *WorkloadPolicyRules
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(WorkloadPolicyRules)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicySpec.
func (in *WorkloadPolicySpec) DeepCopy() *WorkloadPolicySpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadPolicyStatus) DeepCopyInto(out *WorkloadPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadPolicyStatus.
func (in *WorkloadPolicyStatus) DeepCopy() *WorkloadPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
