apiVersion: security.rancher.io/v1alpha1
kind: WorkloadPolicyProposal
metadata:
  name: workloadpolicyproposal-sample
spec:
  rulesByContainer:
    ubuntu:
      executables:
        allowed:
          - /nginx-ingress-controller
