package main

import (
	"fmt"
	"strings"

	corev1 "k8s.io/api/core/v1"
)

const staticPodAnnotation = "kubernetes.io/config.mirror"

type containerID = string

type clusterContainerMeta struct {
	id          containerID
	name        string
	terminating bool
}

func (m *clusterContainerMeta) String() string {
	return fmt.Sprintf("Container(id=%s, name=%s, terminating=%t)", m.id, m.name, m.terminating)
}

type clusterPodView struct {
	id         string
	name       string
	namespace  string
	containers map[containerID]*clusterContainerMeta
}

// extractContainerID from container status layout.
func extractContainerID(containerIDRuntimeFormat string) string {
	// This is the layout of a container inside the pod
	// "containerd://d4813c4da49cbaa50542f86bd077608e5d3da101efef52642346803c4d5a902b"
	// we want to remove the prefix
	ret := containerIDRuntimeFormat
	if idx := strings.Index(ret, "://"); idx != -1 {
		ret = ret[idx+3:]
	}
	return ret
}

func addContainerToPodView(containerStatus *corev1.ContainerStatus, podView *clusterPodView) {
	// First we add the container itself using the cgroup field to understand if it is terminated or not.
	// If it is terminated we can safely skip it during the comparison because the agent cache could have been started after the container termination.
	cID := extractContainerID(containerStatus.ContainerID)
	podView.containers[cID] = &clusterContainerMeta{
		id:          cID,
		name:        containerStatus.Name,
		terminating: containerStatus.State.Terminated != nil,
	}

	// Then we check if the container is restarted looking at the `lastState`
	// If yes, we store it as well since the agent cache will keep it until
	// another restart.
	//
	//   containerStatuses:
	//   - allocatedResources:
	//       memory: 120Mi
	//     containerID: containerd://e3a262b11d9d0a1f32272c0144f34efec589564d769b136270cc3d4f9f868e8c
	//     image: ghcr.io/open-telemetry/demo:2.2.0-accounting
	//     imageID: ghcr.io/open-telemetry/demo@sha256:1c5ec15738cb66b1ead621b155149a2fe39eff307e048561aafefbc987b2492e
	//     lastState:
	//       terminated:
	//         containerID: containerd://d435874907dec19fbea235b42f8fdc68f456d83a91a3b3155cb4d136d152b797
	//         exitCode: 137
	//         finishedAt: "2026-04-22T09:17:55Z"
	//         reason: OOMKilled
	//         startedAt: "2026-04-22T09:10:46Z"
	terminatedStatus := containerStatus.LastTerminationState.Terminated
	if terminatedStatus != nil {
		terminatedCID := extractContainerID(terminatedStatus.ContainerID)
		podView.containers[terminatedCID] = &clusterContainerMeta{
			id:          terminatedCID,
			name:        containerStatus.Name,
			terminating: true,
		}
	}
}

func newClusterPodView(pod *corev1.Pod) *clusterPodView {
	// If this is a static Pod we replace the Pod UID generated by the API server
	// with the one from the annotation.
	podUID := string(pod.UID)
	if pod.Annotations != nil && pod.Annotations[staticPodAnnotation] != "" {
		podUID = pod.Annotations[staticPodAnnotation]
	}

	// We don't assert the labels because they will be different from the ones the NRI find.
	podView := &clusterPodView{
		id:         podUID,
		name:       pod.Name,
		namespace:  pod.Namespace,
		containers: make(map[containerID]*clusterContainerMeta),
	}

	for _, containerStatus := range pod.Status.InitContainerStatuses {
		addContainerToPodView(&containerStatus, podView)
	}
	for _, containerStatus := range pod.Status.ContainerStatuses {
		addContainerToPodView(&containerStatus, podView)
	}
	for _, containerStatus := range pod.Status.EphemeralContainerStatuses {
		addContainerToPodView(&containerStatus, podView)
	}
	return podView
}

func (v *clusterPodView) sortKey() string {
	return v.id
}

func (v *clusterPodView) String() string {
	return fmt.Sprintf("%s/%s (%s)", v.namespace, v.name, v.id)
}

func (v *clusterPodView) getNamespace() string {
	return v.namespace
}

func (v *clusterPodView) getName() string {
	return v.name
}

func (v *clusterPodView) getContainers() map[containerID]*clusterContainerMeta {
	return v.containers
}
